/*
 * hwdef.h for RT-Thread (AP_HAL_RTT)
 * Generated by rtt_hwdef.py from hwdef.dat. Do not edit by hand.
 */
#ifndef HWDEF_H
#define HWDEF_H

#define BOARD_NAME "pixhawk6c_mini"

#define HAL_MCU_STM32H7XX 1
#define HAL_MCU_STM32H743XX 1
/* MCU line: STM32H7xx STM32H743xx */

#define FLASH_SIZE_KB 2048

/* Flash layout for bootloader compatibility */
#define FLASH_RESERVE_START_KB 128
#define FLASH_ORIGIN 0x08020000
#define FLASH_LENGTH_KB 1920

#define OSCILLATOR_HZ 16000000

#define SERIAL_PORT_COUNT 7
#define SERIAL_PORT_0_NAME OTG1
#define SERIAL_PORT_1_NAME UART7
#define SERIAL_PORT_2_NAME UART5
#define SERIAL_PORT_3_NAME USART1
#define SERIAL_PORT_4_NAME UART8
#define SERIAL_PORT_5_NAME USART2
#define SERIAL_PORT_6_NAME USART3
/* SERIAL_ORDER: OTG1 UART7 UART5 USART1 UART8 USART2 USART3 */
#define HAL_RTT_UART_DEVICE_LIST "usb-acm0", "uart7", "uart5", "uart1", "uart8", "uart2", "uart3"

#define APJ_BOARD_ID TARGET_HW_PX4_FMU_V6C

#define HAL_BATT_CURR_PIN 1
#define HAL_BATT_CURR_SCALE 36.36
#define HAL_BATT_VOLT_PIN 0
#define HAL_BATT_VOLT_SCALE 18.18
#define HAL_HAVE_BOARD_VOLTAGE 1

#endif /* HWDEF_H */
