#!/usr/bin/env python3
"""
RT-Thread hwdef script for ArduPilot + AP_HAL_RTT.
Parses hwdef.dat (key-value + optional include), generates hwdef.h and ldscript.ld.
Compatible with Tools/ardupilotwaf/rtt.py: -D/--outdir, --params, hwdef.dat.
"""

import argparse
import os
import re
import sys


def parse_hwdef_file(filepath, base_dir, seen=None):
    """
    Parse a hwdef.dat file: KEY [VALUE...] per line, # comments, optional 'include FILE'.
    Include files are resolved relative to the directory of the current file.
    Returns dict: key -> list of value tokens (last occurrence wins for single-value keys).
    """
    if seen is None:
        seen = set()
    filepath = os.path.normpath(os.path.abspath(filepath))
    if filepath in seen:
        return {}
    seen.add(filepath)
    dirpath = os.path.dirname(filepath)
    result = {}
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if line.lower().startswith('include '):
                    rest = line[8:].strip()
                    if rest:
                        inc_path = os.path.normpath(os.path.join(dirpath, rest))
                        if os.path.isfile(inc_path):
                            sub = parse_hwdef_file(inc_path, base_dir, seen)
                            for k, v in sub.items():
                                result[k] = v
                    continue
                parts = line.split()
                if not parts:
                    continue
                key = parts[0]
                values = parts[1:]
                if key.lower() == 'define' and len(values) >= 1:
                    macro_name = values[0]
                    macro_val = ' '.join(values[1:]) if len(values) > 1 else '1'
                    result['_define_' + macro_name] = [macro_val]
                else:
                    result[key] = values
    except OSError as e:
        raise SystemExit('rtt_hwdef: cannot read {}: {}'.format(filepath, e))
    return result


def get_string(params, key, default=''):
    """Get single value as string; if multiple, join with space."""
    vals = params.get(key, [])
    if not vals:
        return default
    return ' '.join(vals)


def get_int(params, key, default=0):
    """Get single value as int."""
    s = get_string(params, key, '').strip()
    if not s:
        return default
    try:
        return int(s, 0)
    except ValueError:
        return default


def generate_hwdef_h(params, outpath):
    """Generate hwdef.h from parsed params: BOARD_NAME, MCU, FLASH_SIZE_KB, OSCILLATOR_HZ, SERIAL_ORDER -> SERIAL_PORT_COUNT + macros."""
    board = get_string(params, 'BOARD_NAME', 'unknown')
    mcu_tokens = params.get('MCU', [])
    mcu_line = ' '.join(mcu_tokens) if mcu_tokens else 'UNKNOWN'
    flash_kb = get_int(params, 'FLASH_SIZE_KB', 0)
    osc_hz = get_int(params, 'OSCILLATOR_HZ', 0)
    serial_order = params.get('SERIAL_ORDER', [])
    serial_count = len(serial_order)
    apj_id = get_string(params, 'APJ_BOARD_ID', '')

    lines = [
        '/*',
        ' * hwdef.h for RT-Thread (AP_HAL_RTT)',
        ' * Generated by rtt_hwdef.py from hwdef.dat. Do not edit by hand.',
        ' */',
        '#ifndef HWDEF_H',
        '#define HWDEF_H',
        '',
        '#define BOARD_NAME "{}"'.format(board.replace('"', '\\"')),
        '',
    ]
    if mcu_tokens:
        for t in mcu_tokens:
            lines.append('#define HAL_MCU_{} 1'.format(t.upper().replace('.', '_')))
        lines.append('/* MCU line: {} */'.format(mcu_line))
        lines.append('')
    if flash_kb > 0:
        lines.append('#define FLASH_SIZE_KB {}'.format(flash_kb))
        lines.append('')
    # Flash layout: FLASH_RESERVE_START_KB reserves space for bootloader at 0x08000000
    flash_reserve_start = get_int(params, 'FLASH_RESERVE_START_KB', 0)
    flash_bl_load_kb = get_int(params, 'FLASH_BOOTLOADER_LOAD_KB', 0)
    flash_reserve_end = get_int(params, 'FLASH_RESERVE_END_KB', 0)
    if flash_reserve_start > 0 or flash_bl_load_kb > 0:
        lines.append('/* Flash layout for bootloader compatibility */')
        lines.append('#define FLASH_RESERVE_START_KB {}'.format(flash_reserve_start))
        if flash_bl_load_kb > 0:
            lines.append('#define FLASH_BOOTLOADER_LOAD_KB {}'.format(flash_bl_load_kb))
        # App: origin = 0x08000000 + reserve_start, length = total - reserve - reserve_end
        # Bootloader: origin = 0x08000000, length = FLASH_BOOTLOADER_LOAD_KB
        flash_origin = 0x08000000 + flash_reserve_start * 1024
        if flash_reserve_start == 0 and flash_bl_load_kb > 0:
            flash_length_kb = flash_bl_load_kb
        elif flash_kb > 0:
            flash_length_kb = flash_kb - flash_reserve_start - flash_reserve_end
        else:
            flash_length_kb = 0
        lines.append('#define FLASH_ORIGIN 0x{:08x}'.format(flash_origin))
        lines.append('#define FLASH_LENGTH_KB {}'.format(flash_length_kb))
        lines.append('')
    if osc_hz > 0:
        lines.append('#define OSCILLATOR_HZ {}'.format(osc_hz))
        lines.append('')
    lines.append('#define SERIAL_PORT_COUNT {}'.format(serial_count))
    if serial_order:
        for i, name in enumerate(serial_order):
            lines.append('#define SERIAL_PORT_{}_NAME {}'.format(i, name))
        lines.append('/* SERIAL_ORDER: {} */'.format(' '.join(serial_order)))
        # Map SERIAL_ORDER to RTT device names for HAL_RTT_UART_DEVICE_LIST
        device_names = []
        for name in serial_order:
            if name.upper().startswith('OTG'):
                device_names.append('"usb-acm0"')
            elif 'UART' in name.upper() or 'USART' in name.upper():
                m = re.search(r'(\d+)', name)
                device_names.append('"uart{}"'.format(m.group(1) if m else '1'))
            else:
                device_names.append('"uart1"')
        lines.append('#define HAL_RTT_UART_DEVICE_LIST {}'.format(', '.join(device_names)))
        lines.append('')
    if apj_id:
        lines.append('#define APJ_BOARD_ID {}'.format(apj_id))
        lines.append('')
    # Output define KEY value from hwdef.dat (e.g. define HAL_BATT_VOLT_SCALE 18.18)
    for k, v in sorted(params.items()):
        if k.startswith('_define_') and v:
            macro_name = k[8:]  # strip _define_
            macro_val = v[0]
            if macro_val.replace('.', '').replace('-', '').isdigit() or macro_val in ('1', '0'):
                lines.append('#define {} {}'.format(macro_name, macro_val))
            else:
                lines.append('#define {} "{}"'.format(macro_name, macro_val.replace('"', '\\"')))
    # Pass through any other keys as optional defines (e.g. custom board options)
    known = {'BOARD_NAME', 'MCU', 'FLASH_SIZE_KB', 'OSCILLATOR_HZ', 'SERIAL_ORDER', 'APJ_BOARD_ID',
             'FLASH_RESERVE_START_KB', 'FLASH_BOOTLOADER_LOAD_KB', 'FLASH_RESERVE_END_KB', 'include'}
    for k, v in sorted(params.items()):
        if k in known or not v or k.startswith('_define_'):
            continue
        key_define = re.sub(r'[^A-Za-z0-9_]', '_', k).upper()
        if len(v) == 1 and v[0].replace('.', '').isdigit():
            lines.append('#define HWDEF_{} {}'.format(key_define, v[0]))
        elif len(v) == 1:
            lines.append('#define HWDEF_{} "{}"'.format(key_define, v[0].replace('"', '\\"')))
        else:
            lines.append('#define HWDEF_{} {}'.format(key_define, ' '.join(v)))
    lines.append('')
    lines.append('#endif /* HWDEF_H */')
    content = '\n'.join(lines) + '\n'
    try:
        with open(outpath, 'w') as f:
            f.write(content)
    except OSError as e:
        raise SystemExit('rtt_hwdef: cannot write {}: {}'.format(outpath, e))


def generate_ldscript_ld(outpath, rtt_root=None, board_name=None):
    """
    Generate ldscript.ld. Placeholder with ENTRY and a comment.
    If rtt_root exists and a BSP could provide the script, add a note.
    """
    lines = [
        '/*',
        ' * Linker script for RT-Thread + AP_HAL_RTT build.',
    ]
    if rtt_root and os.path.isdir(rtt_root):
        lines.append(' * Actual memory layout may be provided by RTT BSP (e.g. modules/rt-thread/bsp/.../link.lds / *.ld).')
        lines.append(' * 由 BSP 提供时请使用 BSP 的链接脚本。')
    else:
        lines.append(' * Placeholder: minimal script; use BSP linker script when building with RTT.')
    lines.extend([
        ' */',
        '',
        'ENTRY(Reset_Handler)',
        '',
        'SECTIONS',
        '{',
        '    .text : { *(.text*) }',
        '    .data : { *(.data*) }',
        '    .bss  : { *(.bss*) *(COMMON) }',
        '}',
        '',
    ])
    content = '\n'.join(lines) + '\n'
    try:
        with open(outpath, 'w') as f:
            f.write(content)
    except OSError as e:
        raise SystemExit('rtt_hwdef: cannot write {}: {}'.format(outpath, e))


def main():
    parser = argparse.ArgumentParser(
        description='RTT hwdef: parse hwdef.dat, generate hwdef.h and ldscript.ld'
    )
    parser.add_argument('-D', '--outdir', dest='outdir', default=None,
                        help='Output directory for hwdef.h and ldscript.ld')
    parser.add_argument('--params', default='',
                        help='Optional parameters (e.g. default_parameters from waf)')
    parser.add_argument('hwdef', nargs=1, metavar='hwdef.dat',
                        help='Path to hwdef.dat')
    args = parser.parse_args()

    outdir = args.outdir if args.outdir else os.getcwd()
    hwdef_path = args.hwdef[0]
    if not os.path.isfile(hwdef_path):
        print('rtt_hwdef: hwdef file not found: {}'.format(hwdef_path), file=sys.stderr)
        return 1

    base_dir = os.path.dirname(os.path.abspath(hwdef_path))
    params = parse_hwdef_file(hwdef_path, base_dir)

    try:
        os.makedirs(outdir, exist_ok=True)
    except OSError as e:
        print('rtt_hwdef: cannot create outdir {}: {}'.format(outdir, e), file=sys.stderr)
        return 1

    hwdef_h_path = os.path.join(outdir, 'hwdef.h')
    ldscript_path = os.path.join(outdir, 'ldscript.ld')

    generate_hwdef_h(params, hwdef_h_path)
    rtt_root = os.environ.get('RTT_ROOT', os.environ.get('RTT_SOURCE', ''))
    if not rtt_root:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        default_rtt = os.path.normpath(os.path.join(script_dir, '..', '..', '..', '..', 'modules', 'rt-thread'))
        if os.path.isdir(default_rtt):
            rtt_root = default_rtt
    generate_ldscript_ld(ldscript_path, rtt_root=rtt_root, board_name=get_string(params, 'BOARD_NAME'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
