#pragma once

#define AP_QUADRUPED_WAVE_ENABLE 0
#ifndef AP_QUADRUPED_WAVE_ENABLE
# define AP_QUADRUPED_WAVE_ENABLE 0
#endif

#define AP_QUADRUPED_CRAB_ENABLE 1
#ifndef AP_QUADRUPED_CRAB_ENABLE
# define AP_QUADRUPED_CRAB_ENABLE 0
#endif