#pragma once

#define AP_QUADRUPED_WAVE_ENABLE 0
#ifndef AP_QUADRUPED_WAVE_ENABLE
# define AP_QUADRUPED_WAVE_ENABLE 0
#endif

#define AP_QUADRUPED_CRUBE_ENABLE 0
#ifndef AP_QUADRUPED_CRUBE_ENABLE
# define AP_QUADRUPED_CRUBE_ENABLE 0
#endif