#include "Copter.h"

static constexpr uint32_t IMPEDANCE_TARE_SETTLE_MS = 600;
static constexpr uint32_t IMPEDANCE_SENSOR_FAILSAFE_MS = 300;

/*
 * Impedance flight mode — Loiter-based mode with admittance control on the
 * forward (pitch) axis.  Roll, yaw and throttle behave identically to Loiter.
 *
 * Pitch stick input is interpreted as a normalised force reference (-1..+1).
 * CMCU-06A body-X contact force is read in grams and normalised by ADM_FGMAX.
 * An admittance (force -> velocity) filter produces a body-X velocity command
 * that is injected into the Loiter trajectory generator as a NE velocity offset.
 */

const AP_Param::GroupInfo ModeImpedance::var_info[] = {

    // @Param: ADM_GAIN
    // @DisplayName: Admittance force-to-velocity gain / 导纳力到速度增益
    // @Description: EN: Scale from normalized force error to body-X velocity output (m/s per unit force). Set to 0 to disable admittance and behave like Loiter. CN: 归一化力误差到机体系X方向速度的比例增益，数值越大接触响应越快；设为0时关闭导纳效果，接近Loiter行为。
    // @Range: 0.0 20.0
    // @Increment: 0.1
    // @User: Advanced
    AP_GROUPINFO("ADM_GAIN", 1, ModeImpedance, _adm_gain, 0.3f),

    // @Param: ADM_TAU
    // @DisplayName: Admittance time constant / 导纳一阶时间常数
    // @Description: EN: First-order time constant for the admittance velocity response. Larger values make the response softer and slower. CN: 导纳速度响应的一阶时间常数，数值越大越柔和、越慢，数值越小越硬、越快。
    // @Range: 0.05 5.0
    // @Units: s
    // @User: Advanced
    AP_GROUPINFO("ADM_TAU", 2, ModeImpedance, _adm_tau, 0.4f),

    // @Param: ADM_VMAX
    // @DisplayName: Admittance max velocity / 导纳最大速度
    // @Description: EN: Maximum body-X velocity command generated by the admittance controller. CN: 导纳控制器允许输出的最大机体系X方向速度，用于限制接触响应速度。
    // @Range: 0.5 20.0
    // @Units: m/s
    // @User: Advanced
    AP_GROUPINFO("ADM_VMAX", 3, ModeImpedance, _adm_vmax, 1.0f),

    // @Param: ADM_DZ
    // @DisplayName: Admittance stick deadzone / 导纳摇杆死区
    // @Description: EN: Pitch stick deadzone used when converting pilot pitch input to normalized force reference. CN: 将俯仰摇杆输入转换为归一化目标力时使用的死区，用于忽略摇杆微小抖动。
    // @Range: 0.0 0.3
    // @User: Advanced
    AP_GROUPINFO("ADM_DZ", 4, ModeImpedance, _adm_dz, 0.05f),

    // @Param: ADM_FMAX
    // @DisplayName: Admittance force reference limit / 导纳目标力限幅
    // @Description: EN: Maximum absolute normalized force reference commanded by the pitch stick. CN: 俯仰摇杆可指令的最大归一化目标力，限制飞手能给出的接触力目标大小。
    // @Range: 0.1 1.0
    // @User: Advanced
    AP_GROUPINFO("ADM_FMAX", 5, ModeImpedance, _adm_fmax, 0.5f),

    // @Param: ADM_FLPF
    // @DisplayName: Force feedback low-pass frequency / 力反馈低通频率
    // @Description: EN: Cutoff frequency for low-pass filtering the normalized CMCU-06A force feedback. Lower values are smoother but add lag; set 0 to disable. CN: 对CMCU-06A归一化力反馈进行低通滤波的截止频率，越低越平滑但延迟越大；设为0关闭滤波。
    // @Range: 0.0 10.0
    // @Units: Hz
    // @User: Advanced
    AP_GROUPINFO("ADM_FLPF", 6, ModeImpedance, _adm_fest_lpf_hz, 3.0f),

    // @Param: ADM_FGMAX
    // @DisplayName: Admittance force full-scale grams / 导纳满量程力克数
    // @Description: EN: CMCU-06A body-X force in grams that maps to normalized force feedback 1.0. CN: 映射为归一化力反馈1.0的CMCU-06A机体系X方向力值，单位为g，例如1000表示1000g对应1.0。
    // @Range: 1 100000
    // @Units: g
    // @User: Advanced
    AP_GROUPINFO("ADM_FGMAX", 7, ModeImpedance, _adm_force_g_max, 1000.0f),

    // @Param: ADM_FREV
    // @DisplayName: Admittance force reverse / 导纳力方向反转
    // @Description: EN: Reverse the sign of the CMCU-06A body-X force feedback when sensor installation direction is opposite. CN: 当传感器安装方向导致力反馈正负号相反时使用，开启后反转CMCU-06A机体系X方向力反馈符号。
    // @Values: 0:Normal,1:Reversed
    // @User: Advanced
    AP_GROUPINFO("ADM_FREV", 8, ModeImpedance, _adm_force_reverse, 0),

    // @Param: ADM_FDZ
    // @DisplayName: Admittance force feedback deadzone / 导纳力反馈死区
    // @Description: EN: Normalized force feedback deadzone applied after filtering. Feedback smaller than this value is treated as zero to avoid control from small sensor noise. CN: 滤波后归一化力反馈的死区，小于该值的力反馈按0处理，用于避免微小传感器噪声持续触发控制。
    // @Range: 0.0 0.3
    // @Increment: 0.01
    // @User: Advanced
    AP_GROUPINFO("ADM_FDZ", 9, ModeImpedance, _adm_force_dz, 0.02f),

    AP_GROUPEND
};

ModeImpedance::ModeImpedance() : Mode()
{
    AP_Param::setup_object_defaults(this, var_info);
}

bool ModeImpedance::init(bool ignore_checks)
{
    float target_roll_rad, target_pitch_rad;
    update_simple_mode();

    get_pilot_desired_lean_angles_rad(target_roll_rad, target_pitch_rad,
                                      loiter_nav->get_angle_max_rad(),
                                      attitude_control->get_althold_lean_angle_max_rad());

    loiter_nav->set_pilot_desired_acceleration_rad(target_roll_rad, target_pitch_rad);
    loiter_nav->init_target();

    if (!pos_control->D_is_active()) {
        pos_control->D_init_controller();
    }

    pos_control->D_set_max_speed_accel_m(get_pilot_speed_dn_ms(), get_pilot_speed_up_ms(), get_pilot_accel_D_mss());
    pos_control->D_set_correction_speed_accel_m(get_pilot_speed_dn_ms(), get_pilot_speed_up_ms(), get_pilot_accel_D_mss());

    admittance_reset();
    _tare_requested = false;
    _tare_reported = false;
    _tare_start_ms = 0;
    _sensor_failsafe_ms = 0;
#if AP_CMCU06A_ENABLED
    if (!copter.cmcu06a.healthy()) {
        GCS_SEND_TEXT(MAV_SEVERITY_WARNING, "Impedance: CMCU06A not healthy");
        return false;
    }

    if (!copter.cmcu06a.tare()) {
        GCS_SEND_TEXT(MAV_SEVERITY_WARNING, "Impedance: CMCU06A tare busy");
        return false;
    }
    _tare_requested = true;
    _tare_start_ms = AP_HAL::millis();
#endif

    return true;
}

void ModeImpedance::run()
{
    float target_roll_rad, target_pitch_rad;
    float target_yaw_rate_rads = 0.0f;
    float target_climb_rate_ms = 0.0f;
    const uint32_t now_ms = AP_HAL::millis();

    pos_control->D_set_max_speed_accel_m(get_pilot_speed_dn_ms(), get_pilot_speed_up_ms(), get_pilot_accel_D_mss());

    update_simple_mode();

    get_pilot_desired_lean_angles_rad(target_roll_rad, target_pitch_rad,
                                      loiter_nav->get_angle_max_rad(),
                                      attitude_control->get_althold_lean_angle_max_rad());

    // Pitch stick → force reference (sign: push-forward = negative norm_input,
    // but we want push-forward = positive force_ref so negate)
    float pitch_stick_norm = -channel_pitch->norm_input_dz();
    if (fabsf(pitch_stick_norm) < _adm_dz.get()) {
        pitch_stick_norm = 0.0f;
    }
    const float fmax = constrain_float(_adm_fmax.get(), 0.01f, 1.0f);
    _adm_force_ref = constrain_float(pitch_stick_norm, -fmax, fmax);

    bool force_ready = false;
    bool tare_settled = false;
    float raw_fest = 0.0f;
#if AP_CMCU06A_ENABLED
    tare_settled = _tare_requested &&
                   (now_ms - _tare_start_ms >= IMPEDANCE_TARE_SETTLE_MS) &&
                   (copter.cmcu06a.last_tare_ms() >= _tare_start_ms);
    if (tare_settled && !_tare_reported) {
        _tare_reported = true;
        GCS_SEND_TEXT(MAV_SEVERITY_NOTICE, "Impedance: CMCU06A tare OK");
    }
    force_ready = tare_settled && copter.cmcu06a.healthy();
    if (force_ready) {
        const float force_g_max = MAX(_adm_force_g_max.get(), 1.0f);
        raw_fest = constrain_float(float(copter.cmcu06a.get_value()) / force_g_max, -1.0f, 1.0f);
        if (_adm_force_reverse.get() != 0) {
            raw_fest = -raw_fest;
        }
    }
#else
    force_ready = true;
#endif
    if (!force_ready) {
        admittance_reset();
        if (!tare_settled) {
            _sensor_failsafe_ms = 0;
        }
    }

    const float lpf_hz = _adm_fest_lpf_hz.get();
    if (lpf_hz > 0.0f) {
        const float dt = pos_control->get_dt_s();
        const float alpha = constrain_float(dt * lpf_hz * M_2PI, 0.0f, 1.0f);
        _adm_force_est_filt += (raw_fest - _adm_force_est_filt) * alpha;
    } else {
        _adm_force_est_filt = raw_fest;
    }
    const float force_dz = constrain_float(_adm_force_dz.get(), 0.0f, 0.3f);
    _adm_force_est = (fabsf(_adm_force_est_filt) < force_dz) ? 0.0f : _adm_force_est_filt;

#if AP_CMCU06A_ENABLED
    if (!tare_settled) {
        _sensor_failsafe_ms = 0;
    } else if (force_ready) {
        _sensor_failsafe_ms = 0;
    } else if (_sensor_failsafe_ms == 0) {
        _sensor_failsafe_ms = now_ms;
    } else if (now_ms - _sensor_failsafe_ms >= IMPEDANCE_SENSOR_FAILSAFE_MS) {
        admittance_reset();
        copter.set_mode(Mode::Number::ALT_HOLD, ModeReason::UNAVAILABLE);
        return;
    }
#endif

    // Feed a virtual pitch angle proportional to admittance velocity so that
    // Loiter's internal brake/drag logic sees "pilot input" on the forward
    // axis and does not fight the admittance velocity offset.
    _virtual_pitch_rad = 0.0f;
    if (!is_zero(_adm_v_body_x)) {
        const float speed_max = MAX(loiter_nav->get_speed_max_NE_ms(), 0.1f);
        const float angle_max = loiter_nav->get_angle_max_rad();
        _virtual_pitch_rad = -(_adm_v_body_x / speed_max) * angle_max;
        _virtual_pitch_rad = constrain_float(_virtual_pitch_rad, -angle_max, angle_max);
    }
    loiter_nav->set_pilot_desired_acceleration_rad(target_roll_rad, _virtual_pitch_rad);

    target_yaw_rate_rads = get_pilot_desired_yaw_rate_rads();

    target_climb_rate_ms = get_pilot_desired_climb_rate_ms();
    target_climb_rate_ms = constrain_float(target_climb_rate_ms, -get_pilot_speed_dn_ms(), get_pilot_speed_up_ms());

    if (copter.ap.land_complete_maybe) {
        loiter_nav->soften_for_landing();
    }

    AltHoldModeState imp_state = get_alt_hold_state_D_ms(target_climb_rate_ms);

    switch (imp_state) {

    case AltHoldModeState::MotorStopped:
        admittance_reset();
        attitude_control->reset_rate_controller_I_terms();
        attitude_control->reset_yaw_target_and_rate();
        pos_control->D_relax_controller(0.0f);
        loiter_nav->init_target();
        break;

    case AltHoldModeState::Landed_Ground_Idle:
        admittance_reset();
        attitude_control->reset_yaw_target_and_rate();
        FALLTHROUGH;

    case AltHoldModeState::Landed_Pre_Takeoff:
        admittance_reset();
        attitude_control->reset_rate_controller_I_terms_smoothly();
        loiter_nav->init_target();
        pos_control->D_relax_controller(0.0f);
        break;

    case AltHoldModeState::Takeoff:
        admittance_reset();
        if (!takeoff.running()) {
            takeoff.start_m(constrain_float(g2.pilot_takeoff_alt_m, 0.0, 10.0));
        }
        target_climb_rate_ms = get_avoidance_adjusted_climbrate_ms(target_climb_rate_ms);
        takeoff.do_pilot_takeoff_ms(target_climb_rate_ms);
        loiter_nav->update();
        break;

    case AltHoldModeState::Flying:
        if (force_ready) {
            admittance_update(pos_control->get_dt_s());
        }
        loiter_nav->update();

#if HAL_LOGGING_ENABLED
        copter.Log_Write_Impedance(
            _adm_force_ref, _adm_force_est,
            _adm_force_ref - _adm_force_est,
            _adm_v_body_x,
            _vel_offset_ne.x, _vel_offset_ne.y,
            _virtual_pitch_rad);
#endif

        target_climb_rate_ms = get_avoidance_adjusted_climbrate_ms(target_climb_rate_ms);

#if AP_RANGEFINDER_ENABLED
        copter.surface_tracking.update_surface_offset();
#endif

        pos_control->D_set_pos_target_from_climb_rate_ms(target_climb_rate_ms);
        break;
    }

    attitude_control->input_thrust_vector_rate_heading_rads(loiter_nav->get_thrust_vector(), target_yaw_rate_rads, false);
    pos_control->D_update_controller();
}

float ModeImpedance::wp_distance_m() const
{
    return loiter_nav->get_distance_to_target_m();
}

float ModeImpedance::wp_bearing_deg() const
{
    return degrees(loiter_nav->get_bearing_to_target_rad());
}

void ModeImpedance::admittance_reset()
{
    _adm_v_body_x = 0.0f;
    _adm_force_ref = 0.0f;
    _adm_force_est = 0.0f;
    _adm_force_est_filt = 0.0f;
    _virtual_pitch_rad = 0.0f;
    _vel_offset_ne.zero();
    loiter_nav->clear_vel_offset_NE_ms();
}

void ModeImpedance::admittance_update(float dt)
{
    if (dt <= 0.0f || dt > 0.1f) {
        return;
    }

    const float force_err = _adm_force_ref - _adm_force_est;
    const float gain = _adm_gain.get();
    const float tau  = MAX(_adm_tau.get(), 0.01f);
    const float vmax = _adm_vmax.get();

    _adm_v_body_x += (gain * force_err - _adm_v_body_x) * (dt / tau);
    _adm_v_body_x = constrain_float(_adm_v_body_x, -vmax, vmax);

    _vel_offset_ne.x = _adm_v_body_x * ahrs.cos_yaw();
    _vel_offset_ne.y = _adm_v_body_x * ahrs.sin_yaw();

    loiter_nav->set_vel_offset_NE_ms(_vel_offset_ne);
}
